from __future__ import annotations

import os


def _bool_env(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off", ""}


ENABLE = _bool_env("HISTORY_PLACEMENT_ENABLE", True)
OUTPUT_MODE = os.environ.get("HISTORY_PLACEMENT_OUTPUT_MODE", "minimal_output")
FULL_OUTPUT = _bool_env("HISTORY_PLACEMENT_FULL_OUTPUT", OUTPUT_MODE == "full_output")

DEFAULT_MODEL_LIMIT = int(os.environ.get("HISTORY_PLACEMENT_DEFAULT_MODEL_LIMIT", "5"))
BASELINE_PRE_CAPTURE_LOOKBACK_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_BASELINE_PRE_CAPTURE_LOOKBACK_SECONDS", "120"))
BASELINE_POST_CAPTURE_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_BASELINE_POST_CAPTURE_SECONDS", "60"))
CURRENT_LOOKBACK_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_CURRENT_LOOKBACK_SECONDS", "12"))
CURRENT_FORWARD_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_CURRENT_FORWARD_SECONDS", "0"))
RECENT_UNIQUE_COUNT = int(os.environ.get("HISTORY_PLACEMENT_RECENT_UNIQUE_COUNT", "5"))
STABLE_UNIQUE_COUNT = int(os.environ.get("HISTORY_PLACEMENT_STABLE_UNIQUE_COUNT", "3"))
MISSING_UNIQUE_COUNT = int(os.environ.get("HISTORY_PLACEMENT_MISSING_UNIQUE_COUNT", "3"))

YOLO_MATCH_MAX_CENTER_PX = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MATCH_MAX_CENTER_PX", "250"))
YOLO_MATCH_DEPTH_TOLERANCE_M = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MATCH_DEPTH_TOLERANCE_M", "0.45"))
YOLO_MATCH_MAX_SCORE = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MATCH_MAX_SCORE", "4.25"))
YOLO_MIN_MASK_PIXELS = int(os.environ.get("HISTORY_PLACEMENT_YOLO_MIN_MASK_PIXELS", "16"))

ORIGINAL_MAX_CENTER_PX = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_CENTER_PX", "45"))
ORIGINAL_MAX_CENTER_BBOX_RATIO = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_CENTER_BBOX_RATIO", "0.18"))
ORIGINAL_MAX_DEPTH_DELTA_M = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_DEPTH_DELTA_M", "0.22"))
ORIGINAL_MAX_ARUCO_DELTA_M = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_ARUCO_DELTA_M", "0.14"))

SIGNATURE_MAX_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_SCORE", "2.75"))
SIGNATURE_COLOR_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_COLOR_WEIGHT", "1.0"))
SIGNATURE_AREA_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_AREA_WEIGHT", "0.55"))
SIGNATURE_ASPECT_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_ASPECT_WEIGHT", "0.45"))
SIGNATURE_DEPTH_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_DEPTH_WEIGHT", "0.35"))

OCCLUSION_DELTA_M = -abs(float(os.environ.get("HISTORY_PLACEMENT_OCCLUSION_DELTA_M", "0.10")))
OCCLUSION_CLOSER_RATIO = float(os.environ.get("HISTORY_PLACEMENT_OCCLUSION_CLOSER_RATIO", "0.25"))
MISSING_DELTA_M = abs(float(os.environ.get("HISTORY_PLACEMENT_MISSING_DELTA_M", "0.10")))
MISSING_DEEPER_RATIO = float(os.environ.get("HISTORY_PLACEMENT_MISSING_DEEPER_RATIO", "0.40"))

POLYHEDRON_EDGE_LENGTH_M = float(os.environ.get("HISTORY_PLACEMENT_POLYHEDRON_EDGE_LENGTH_M", "0.10"))
POLYHEDRON_ABOVE_MARGIN_M = float(os.environ.get("HISTORY_PLACEMENT_POLYHEDRON_ABOVE_MARGIN_M", "0.10"))
ANIMATION_DURATION_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_ANIMATION_DURATION_SECONDS", "1.2"))
