from __future__ import annotations

import os


def _bool_env(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off", ""}


ENABLE = _bool_env("HISTORY_PLACEMENT_ENABLE", True)
OUTPUT_MODE = os.environ.get("HISTORY_PLACEMENT_OUTPUT_MODE", "minimal_output")
FULL_OUTPUT = _bool_env("HISTORY_PLACEMENT_FULL_OUTPUT", OUTPUT_MODE == "full_output")

DEFAULT_MODEL_LIMIT = int(os.environ.get("HISTORY_PLACEMENT_DEFAULT_MODEL_LIMIT", "5"))
PARALLEL_WORKERS = int(os.environ.get("HISTORY_PLACEMENT_MAX_PARALLEL_ITEMS", "8"))
BASELINE_POST_CAPTURE_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_BASELINE_POST_CAPTURE_SECONDS", "60"))

YOLO_NEAREST_SEARCH_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_YOLO_NEAREST_SEARCH_SECONDS", "12"))
YOLO_MAX_DELTA_TO_TARGET_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MAX_DELTA_TO_TARGET_SECONDS", "12"))
TRACKING_REGION_YOLO_IDS = tuple(
    value.strip()
    for value in os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_YOLO_IDS", "340").split(",")
    if value.strip()
)
TRACKING_REGION_INVALID_POLICY = os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_INVALID_POLICY", "unknown").strip().lower()
TRACKING_REGION_SUPPORT_MAX_BEHIND_DEPTH_M = float(os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_SUPPORT_MAX_BEHIND_DEPTH_M", "0.08"))
TRACKING_REGION_SUPPORT_STATIC_DEPTH_DELTA_M = float(os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_SUPPORT_STATIC_DEPTH_DELTA_M", "0.08"))
TRACKING_REGION_SUPPORT_STATIC_CENTER_DELTA_PX = float(os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_SUPPORT_STATIC_CENTER_DELTA_PX", "80"))

TRACKING_REGION_DUPLICATE_MIN_IOU = float(os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_DUPLICATE_MIN_IOU", "0.80"))
TRACKING_REGION_DUPLICATE_MAX_CENTER_DELTA_PX = float(os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_DUPLICATE_MAX_CENTER_DELTA_PX", "25"))
TRACKING_REGION_DUPLICATE_MAX_DEPTH_DELTA_M = float(os.environ.get("HISTORY_PLACEMENT_TRACKING_REGION_DUPLICATE_MAX_DEPTH_DELTA_M", "0.05"))

YOLO_MATCH_MAX_CENTER_PX = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MATCH_MAX_CENTER_PX", "250"))
YOLO_MATCH_DEPTH_TOLERANCE_M = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MATCH_DEPTH_TOLERANCE_M", "0.45"))
YOLO_MATCH_MAX_SCORE = float(os.environ.get("HISTORY_PLACEMENT_YOLO_MATCH_MAX_SCORE", "4.25"))
YOLO_MIN_MASK_PIXELS = int(os.environ.get("HISTORY_PLACEMENT_YOLO_MIN_MASK_PIXELS", "16"))

ORIGINAL_MAX_CENTER_PX = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_CENTER_PX", "45"))
ORIGINAL_MAX_CENTER_BBOX_RATIO = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_CENTER_BBOX_RATIO", "0.18"))
ORIGINAL_MAX_DEPTH_DELTA_M = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_DEPTH_DELTA_M", "0.22"))
ORIGINAL_MAX_ARUCO_DELTA_M = float(os.environ.get("HISTORY_PLACEMENT_ORIGINAL_MAX_ARUCO_DELTA_M", "0.14"))

SIGNATURE_MAX_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_SCORE", "2.75"))
SIGNATURE_MAX_VISUAL_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_VISUAL_SCORE", "0.70"))
SIGNATURE_MAX_MODEL_SIZE_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_MODEL_SIZE_SCORE", "1.15"))
SIGNATURE_MAX_MODEL_LARGEST_DIM_RATIO = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_MODEL_LARGEST_DIM_RATIO", "3.0"))
SIGNATURE_MAX_MODEL_TOP2_AREA_RATIO = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_MODEL_TOP2_AREA_RATIO", "4.0"))
SIGNATURE_MAX_SHAPE_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_SHAPE_SCORE", "1.00"))
SIGNATURE_MAX_DEPTH_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_DEPTH_SCORE", "1.40"))
SIGNATURE_MAX_CHANGE_SCORE = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MAX_CHANGE_SCORE", "0.97"))
SIGNATURE_VISUAL_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_VISUAL_WEIGHT", "1.05"))
SIGNATURE_MODEL_SIZE_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_MODEL_SIZE_WEIGHT", "0.70"))
SIGNATURE_SHAPE_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_SHAPE_WEIGHT", "0.30"))
SIGNATURE_DEPTH_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_DEPTH_WEIGHT", "0.20"))
SIGNATURE_CHANGE_WEIGHT = float(os.environ.get("HISTORY_PLACEMENT_SIGNATURE_CHANGE_WEIGHT", "0.35"))
CHANGE_RGB_DIFF_THRESHOLD = float(os.environ.get("HISTORY_PLACEMENT_CHANGE_RGB_DIFF_THRESHOLD", "28"))
CHANGE_DEPTH_DIFF_THRESHOLD_M = float(os.environ.get("HISTORY_PLACEMENT_CHANGE_DEPTH_DIFF_THRESHOLD_M", "0.08"))
CHANGE_MORPH_KERNEL_PX = int(os.environ.get("HISTORY_PLACEMENT_CHANGE_MORPH_KERNEL_PX", "7"))
CANDIDATE_MIN_CHANGE_OVERLAP_RATIO = float(os.environ.get("HISTORY_PLACEMENT_CANDIDATE_MIN_CHANGE_OVERLAP_RATIO", "0.03"))

OCCLUSION_DELTA_M = -abs(float(os.environ.get("HISTORY_PLACEMENT_OCCLUSION_DELTA_M", "0.10")))
OCCLUSION_CLOSER_RATIO = float(os.environ.get("HISTORY_PLACEMENT_OCCLUSION_CLOSER_RATIO", "0.25"))
MISSING_DELTA_M = abs(float(os.environ.get("HISTORY_PLACEMENT_MISSING_DELTA_M", "0.10")))
MISSING_DEEPER_RATIO = float(os.environ.get("HISTORY_PLACEMENT_MISSING_DEEPER_RATIO", "0.40"))

POLYHEDRON_EDGE_LENGTH_M = float(os.environ.get("HISTORY_PLACEMENT_POLYHEDRON_EDGE_LENGTH_M", "0.10"))
POLYHEDRON_ABOVE_MARGIN_M = float(os.environ.get("HISTORY_PLACEMENT_POLYHEDRON_ABOVE_MARGIN_M", "0.08"))
ANIMATION_DURATION_SECONDS = float(os.environ.get("HISTORY_PLACEMENT_ANIMATION_DURATION_SECONDS", "1.2"))
