from __future__ import annotations

import os


def _bool_env(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off", ""}


# State-machine timing.
TRACKING_DURATION_SECONDS = float(os.environ.get("TAKEN_OBJECT_TRACKING_DURATION_SECONDS", "600"))
INIT_MAX_START_DELAY_SECONDS = float(os.environ.get("TAKEN_OBJECT_INIT_MAX_START_DELAY_SECONDS", "60"))
INIT_TIMEOUT_SECONDS = float(os.environ.get("TAKEN_OBJECT_INIT_TIMEOUT_SECONDS", "60"))
INIT_STABLE_WINDOW_SECONDS = float(os.environ.get("TAKEN_OBJECT_INIT_STABLE_WINDOW_SECONDS", "3"))
OFFLINE_STOP_WHEN_HISTORY_EXHAUSTED = _bool_env("TAKEN_OBJECT_OFFLINE_STOP_WHEN_HISTORY_EXHAUSTED", True)

# Depth thresholds, in meters.
INIT_STABLE_DEPTH_DELTA_M = float(os.environ.get("TAKEN_OBJECT_INIT_STABLE_DEPTH_DELTA_M", "0.1"))
DEPTH_MARGIN_M = float(os.environ.get("TAKEN_OBJECT_DEPTH_MARGIN_M", "0.1"))
OCCLUSION_DELTA_M = -abs(float(os.environ.get("TAKEN_OBJECT_OCCLUSION_DELTA_M", "0.1")))
TAKEN_DELTA_M = abs(float(os.environ.get("TAKEN_OBJECT_TAKEN_DELTA_M", "0.1")))

# Pixel ratios.
INIT_STABLE_PIXEL_RATIO = float(os.environ.get("TAKEN_OBJECT_INIT_STABLE_PIXEL_RATIO", "0.95"))
TRUSTED_MASK_MIN_IMAGE_RATIO = float(os.environ.get("TAKEN_OBJECT_TRUSTED_MASK_MIN_IMAGE_RATIO", "0.003"))
FULL_OCCLUSION_RATIO = float(os.environ.get("TAKEN_OBJECT_FULL_OCCLUSION_RATIO", "0.90"))
TAKEN_RATIO = float(os.environ.get("TAKEN_OBJECT_TAKEN_RATIO", "0.40"))
TAKEN_CONSECUTIVE_FRAMES = int(os.environ.get("TAKEN_OBJECT_TAKEN_CONSECUTIVE_FRAMES", "3"))
PARTIAL_OCCLUSION_CLOSER_RATIO = float(os.environ.get("TAKEN_OBJECT_PARTIAL_OCCLUSION_CLOSER_RATIO", "0.25"))
PARTIAL_OCCLUSION_UNCHANGED_RATIO = float(os.environ.get("TAKEN_OBJECT_PARTIAL_OCCLUSION_UNCHANGED_RATIO", "0.25"))
PARTIAL_OCCLUSION_DEEPER_MAX_RATIO = float(os.environ.get("TAKEN_OBJECT_PARTIAL_OCCLUSION_DEEPER_MAX_RATIO", "0.15"))

# RGB backtracking.
RGB_BACKTRACK_SECONDS = float(os.environ.get("TAKEN_OBJECT_RGB_BACKTRACK_SECONDS", "5"))
RGB_ADJACENT_DIFF_THRESHOLD = float(os.environ.get("TAKEN_OBJECT_RGB_ADJACENT_DIFF_THRESHOLD", "18"))
RGB_INIT_DIFF_THRESHOLD = float(os.environ.get("TAKEN_OBJECT_RGB_INIT_DIFF_THRESHOLD", "24"))

# Output and fallback controls.
OUTPUT_MODE = os.environ.get("TAKEN_OBJECT_OUTPUT_MODE", "minimal_output")
FULL_OUTPUT = _bool_env("TAKEN_OBJECT_FULL_OUTPUT", OUTPUT_MODE == "full_output")
ALLOW_SELECTION_BOX_MASK_FALLBACK = _bool_env("TAKEN_OBJECT_ALLOW_SELECTION_BOX_MASK_FALLBACK", True)
TRACKING_MODE = os.environ.get("TAKEN_OBJECT_TRACKING_MODE", "model_box_depth").strip().lower()
ENABLE_LEGACY_PROJECTED_MASK = _bool_env("TAKEN_OBJECT_ENABLE_LEGACY_PROJECTED_MASK", False)
ENABLE_LEGACY_FALLBACK = _bool_env("TAKEN_OBJECT_ENABLE_LEGACY_FALLBACK", True)

# YOLO-first initialization and coarse tracking.
YOLO_PRE_CAPTURE_UNIQUE_COUNT = int(os.environ.get("TAKEN_OBJECT_YOLO_PRE_CAPTURE_UNIQUE_COUNT", "3"))
YOLO_PRE_CAPTURE_LOOKBACK_SECONDS = float(os.environ.get("TAKEN_OBJECT_YOLO_PRE_CAPTURE_LOOKBACK_SECONDS", "120"))
YOLO_INIT_STABLE_UNIQUE_COUNT = int(os.environ.get("TAKEN_OBJECT_YOLO_INIT_STABLE_UNIQUE_COUNT", "3"))
YOLO_INIT_SOFT_TIMEOUT_SECONDS = float(os.environ.get("TAKEN_OBJECT_YOLO_INIT_SOFT_TIMEOUT_SECONDS", "30"))
YOLO_INIT_HARD_TIMEOUT_SECONDS = float(os.environ.get("TAKEN_OBJECT_YOLO_INIT_HARD_TIMEOUT_SECONDS", "60"))
YOLO_MATCH_MAX_CENTER_PX = float(os.environ.get("TAKEN_OBJECT_YOLO_MATCH_MAX_CENTER_PX", "250"))
YOLO_MATCH_DEPTH_TOLERANCE_M = float(os.environ.get("TAKEN_OBJECT_YOLO_MATCH_DEPTH_TOLERANCE_M", "0.35"))
YOLO_MATCH_MAX_SCORE = float(os.environ.get("TAKEN_OBJECT_YOLO_MATCH_MAX_SCORE", "4.0"))
YOLO_STABLE_MAX_CENTER_PX = float(os.environ.get("TAKEN_OBJECT_YOLO_STABLE_MAX_CENTER_PX", "40"))
YOLO_STABLE_MAX_CENTER_BBOX_RATIO = float(os.environ.get("TAKEN_OBJECT_YOLO_STABLE_MAX_CENTER_BBOX_RATIO", "0.10"))
YOLO_STABLE_MIN_MASK_IOU = float(os.environ.get("TAKEN_OBJECT_YOLO_STABLE_MIN_MASK_IOU", "0.55"))
YOLO_STABLE_MAX_DEPTH_DELTA_M = float(os.environ.get("TAKEN_OBJECT_YOLO_STABLE_MAX_DEPTH_DELTA_M", "0.20"))
YOLO_MOVE_CENTER_PX = float(os.environ.get("TAKEN_OBJECT_YOLO_MOVE_CENTER_PX", "40"))
YOLO_MOVE_CENTER_BBOX_RATIO = float(os.environ.get("TAKEN_OBJECT_YOLO_MOVE_CENTER_BBOX_RATIO", "0.15"))
YOLO_MOVE_STRONG_CENTER_PX = float(os.environ.get("TAKEN_OBJECT_YOLO_MOVE_STRONG_CENTER_PX", "80"))
YOLO_MOVE_STRONG_BBOX_RATIO = float(os.environ.get("TAKEN_OBJECT_YOLO_MOVE_STRONG_BBOX_RATIO", "0.30"))
YOLO_MOVE_STABLE_UNIQUE_COUNT = int(os.environ.get("TAKEN_OBJECT_YOLO_MOVE_STABLE_UNIQUE_COUNT", "2"))
YOLO_TRACKING_TRIGGER_MODE = os.environ.get("TAKEN_OBJECT_YOLO_TRACKING_TRIGGER_MODE", "direct_depth_scan").strip().lower()

# Model-box-first initialization.
MODEL_BOX_PADDING_PX = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_PADDING_PX", "8"))
MODEL_BOX_PADDING_RATIO = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_PADDING_RATIO", "0.08"))
MODEL_BOX_DEPTH_MARGIN_M = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_DEPTH_MARGIN_M", "0.18"))
MODEL_BOX_INIT_MAX_OCCLUSION_RATIO = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_INIT_MAX_OCCLUSION_RATIO", "0.25"))
MODEL_BOX_MIN_TRUSTED_PIXELS = int(os.environ.get("TAKEN_OBJECT_MODEL_BOX_MIN_TRUSTED_PIXELS", "64"))
MODEL_BOX_CANDIDATE_MAX_CENTER_PX = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MAX_CENTER_PX", "260"))
MODEL_BOX_CANDIDATE_MAX_DEPTH_DIFF_M = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MAX_DEPTH_DIFF_M", "0.65"))
MODEL_BOX_CANDIDATE_MIN_MASK_OVERLAP_RATIO = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MIN_MASK_OVERLAP_RATIO", "0.05"))
MODEL_BOX_CANDIDATE_MIN_BBOX_IOU = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MIN_BBOX_IOU", "0.02"))
MODEL_BOX_CANDIDATE_MIN_AREA_RATIO = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MIN_AREA_RATIO", "0.03"))
MODEL_BOX_CANDIDATE_MAX_AREA_RATIO = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MAX_AREA_RATIO", "6.0"))
MODEL_BOX_CANDIDATE_MAX_SCORE = float(os.environ.get("TAKEN_OBJECT_MODEL_BOX_CANDIDATE_MAX_SCORE", "4.5"))
