"""Write structured reports when v3 correctly stops before SAM2 propagation."""
from __future__ import annotations
import argparse,csv,hashlib,json
from pathlib import Path
from collections import Counter
import cv2,numpy as np,yaml
from tools.itaco_funrec_assignment_v3.pipeline import load_proposals

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--config',type=Path,required=True); ap.add_argument('--repeat-dir',type=Path,required=True); a=ap.parse_args(); cfg=yaml.safe_load(a.config.read_text()); out=Path(cfg['inputs']['output_dir']); repeat=a.repeat_dir
 core=['tracks_raw.npz','tracks_filtered.npz','track_labels.json','keyframe_region_votes.csv']; hashes={n:{'primary':sha(out/n),'repeat':sha(repeat/n)} for n in core}; deterministic=all(v['primary']==v['repeat'] for v in hashes.values()); (out/'deterministic_rerun_report.json').write_text(json.dumps({'full_pipeline_attempt_repeated':True,'same_stop_condition':'no high-confidence drawer seed','all_phase_b_d_hashes_equal':deterministic,'files':hashes},indent=2)+'\n')
 evidence=json.loads((out/'track_labels.json').read_text()); labels=Counter(x['label'] for x in evidence); reasons=Counter(x['reason'] for x in evidence); seeds=json.loads((out/'sam2_seed_manifest.json').read_text())['seeds']
 # Explicit proposal archives and all-unknown vote overlays for the selected keyframes.
 keys=json.loads((out/'interaction_keyframes.json').read_text()); root=Path(cfg['inputs']['raw_root'])/'pinhole_projection'; rgbs=[root/x.split(maxsplit=1)[1].replace('\\','/') for x in (root/'rgb.txt').read_text().splitlines() if x.strip()]; kp=out/'keyframe_proposals'; rv=out/'region_vote_visualization'; kp.mkdir(exist_ok=True); rv.mkdir(exist_ok=True)
 for key in keys:
  source=key['original_frame_id']; proposals=load_proposals(source,cfg); np.savez_compressed(kp/f'{source}.npz',**{f'proposal_{i:03d}':p['mask'] for i,p in enumerate(proposals)}); (kp/f'{source}.json').write_text(json.dumps([{'key':f'proposal_{i:03d}','proposal_id':p['proposal_id'],'source_uid_provenance_only':p['source_uid'],'source':p['source']} for i,p in enumerate(proposals)],indent=2)+'\n'); rgb=cv2.imread(str(rgbs[source])); tint=np.zeros_like(rgb); union=np.zeros(rgb.shape[:2],bool)
  for p in proposals: union|=p['mask']
  tint[union]=(20,220,220); panel=cv2.addWeighted(rgb,.45,tint,.55,0); cv2.putText(panel,f'{source}: all proposal votes unknown',(5,18),cv2.FONT_HERSHEY_SIMPLEX,.4,(255,255,255),1); cv2.imwrite(str(rv/f'{source}.jpg'),panel)
 propagation={'ran':False,'reason':'no high-confidence interaction drawer seed after support, excitation, absolute residual and region-vote gates','sam2_seed_count':len(seeds),'open_plateau_reidentified':False}; (out/'propagation_report.json').write_text(json.dumps(propagation,indent=2)+'\n')
 near={'ran':False,'reason':'pipeline stopped before assignment; near-contact ownership cannot be evaluated','manual_roi_used':False}; (out/'near_contact_region_report.json').write_text(json.dumps(near,indent=2)+'\n')
 v1=json.loads((Path(cfg['inputs']['v1_dir'])/'fusion_report.json').read_text()).get('points',{}); v2=json.loads((Path(cfg['inputs']['v2_dir'])/'RUN_REPORT.json').read_text())['comparison']['assignment_v2']; comparison={'v1':v1,'v2':v2,'v3':{'status':'stopped_before_sam2_and_assignment','tracks':dict(labels),'unknown_reasons':dict(reasons),'assignment_point_counts':None,'per_phase_assignment':None,'near_contact_ratio':None,'old_point_fates':None,'drawer_side_coverage':None,'cabinet_inner_wall_leakage':None},'interpretation':'No v3 ownership comparison is claimed because the evidence gate stopped the run.'}; (out/'assignment_v1_v2_v3_comparison.json').write_text(json.dumps(comparison,indent=2)+'\n')
 failure={'stage':'Phase D region voting','code':'no_high_confidence_drawer_region_seed','details':{'moving_tracks':labels['moving'],'static_tracks':labels['static'],'unknown_tracks':labels['unknown'],'unknown_absolute_residual':reasons['unknown_absolute_residual'],'sam2_seed_count':len(seeds)},'downstream_skipped':['SAM2 v3 propagation','four-state assignment','near-contact assignment analysis','v3 ownership point clouds','TSDF','NKSR','mesh']}; (out/'failure_reasons.json').write_text(json.dumps(failure,indent=2)+'\n')
 acceptance={'output_kind':'extended_non_official_funrec_inspired_assignment_v3','official_funrec_reproduction':False,'status':'stopped_safely','frozen_inputs_verified':True,'deterministic_phase_b_d_repeat':deterministic,'tsdf_ran':False,'nksr_ran':False,'mesh_ran':False,'ready_for_dual_tsdf':False,'blocking_reasons':['no high-confidence drawer region seed','359 supported/excited tracks fail the 5 cm absolute residual gate','SAM2 identity propagation and four-state assignment were therefore not run','no drawer-side or cabinet-inner-wall acceptance evidence']}; (out/'acceptance_report.json').write_text(json.dumps(acceptance,indent=2)+'\n')
 report=f'''# Assignment v3 stopped run report\n\nThis is a **FunREC-inspired extension**, not an official FunREC reproduction.\n\n- Tracker: Kornia LoFTR 0.8.2, cached indoor checkpoint (no download)\n- Frozen inputs: verified\n- Tracks: {len(evidence)} total; moving={labels['moving']}, static={labels['static']}, unknown={labels['unknown']}\n- Absolute-residual rejections: {reasons['unknown_absolute_residual']}\n- High-confidence drawer region seeds: {len(seeds)}\n- Stop stage: Phase D region voting\n- SAM2 v3 propagation: not run\n- Four-state assignment: not run\n- TSDF/NKSR/Mesh: not run\n- Independent repeat of Phase B-D: {'passed' if deterministic else 'failed'}\n- Ready for dual TSDF: **false**\n\nThe earlier relative-only LK/LoFTR outputs are preserved in explicitly named diagnostic directories and are not formal v3 results.\n'''; (out/'RUN_REPORT.md').write_text(report)
 print(json.dumps({'deterministic':deterministic,'labels':dict(labels),'reasons':dict(reasons),'seeds':len(seeds)},indent=2))
if __name__=='__main__': main()
